### ISSUE TITLE
Better java management

### ISSUE THREAD

**Issue by stairman06** [theemeraldtree/minecraft-manager#26]
The bundles Java version in the Minecraft Launcher is old and out of date; the ability to download different versions of java is important.

**Comment by riskable** [comment]
Yeah, I don't want to have to just trust your version of java.  Let me use my own version...  Provide a mechanism to set a path to the java executable and also specify the arguments (like MultiMC).

A wrapper command would also be helpful so I could use things like the `gamemoderun` wrapper (https://github.com/FeralInteractive/gamemode).

**Comment by stairman06** [comment]
As a temporary solution, because Minecraft Manager uses the native Minecraft Launcher, you can change the Java executable path in there.
![image](https://user-images.githubusercontent.com/36215135/82844038-9d5a7e00-9ea4-11ea-95c0-35bb73187593.png)

For Mac and Linux users, everything should work the same way. You can use Minecraft Manager as you normally would. For Windows users, you won't be able to launch through Minecraft Manager. You'll need to open the regular Minecraft launcher and select the profile from there.

Custom argument support and wrapper commands are also a good idea - I'll be working on that.

**Comment by stairman06** [comment]
Better Java support is done in 2.5.0 in the work branch - release should be relatively soon.
