### ISSUE TITLE
[BUG] Doesn't seem to work (just forever loading)

### ISSUE THREAD

**Issue by riskable** [theemeraldtree/minecraft-manager#27]
**Describe the bug**

Downloaded the .AppImage, set it excutable, and ran it (Kubuntu 20.04).  Just sits forever like this:

![Screenshot_20200525_164702](https://user-images.githubusercontent.com/66987/82842425-76ea1200-9ea7-11ea-8e1b-20cc9e3a47d5.png)

**Expected behavior**

Expected an interface of some sort.  Also expected to be able to get something like "About..." in the help menu so I could quickly check the version string.

**Reproduce**

1. Download the current .AppImage and try to run it.

**System Info**

Please provide system and application information

OS: Kubuntu 20.04 (same as Ubuntu)
Minecraft Manager Version: Whatever was there 5 minutes ago.

**Comment by stairman06** [comment]
Thanks for the bug report! I'll check this out in a VM and see whats going on.

**Comment by stairman06** [comment]
@riskable  I've released version 2.4.7 which patches this issue!

_Unfortunately,_ Java continues to be an issue. The default version used by the Minecraft installer (OpenJDK 11) isn't very compatible with modded Minecraft. Better handling of Java versions will be coming soon, but in the meantime there's a way to mitigate the problem.

If you've already messed with Java and have an older version already installed that works, you won't need to follow these instructions. However if you don't and Minecraft crashes immediately upon launching a modded profile, then these steps may help:
1. Install an older version of Java through the terminal. `sudo apt install openjdk-8-jre`
2. Find the path of the Java binary `update-java-alternatives --list`. You'll want to look for the path next to "java-1.8.0...". Mine was "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
3. Everytime you create a new Profile in Minecraft Manager or download a modpack, you'll need to open the regular Minecraft launcher, click "Installations," then click the profile you want to use. Click "More options," and change "Java Executable" to the path found in step 2, but add "/bin/java" to the end.

Your full Java Executable path in the Minecraft Launcher should be similar to "/usr/lib/jvm-java-1.8.0-openjdk-amd64/bin/java"

I hope this helps!

**Comment by stairman06** [comment]
Closing this issue as this problem should be fixed - if you encounter another problem please file a new issue.
